// Target API Checkout Engine
//
// Executes Target's checkout flow entirely via HTTP — no DOM automation.
// This is the approach used by Stellar AIO and Refract: bypass the browser
// UI and send requests directly to Target's internal cart/checkout APIs.
//
// Flow:
//   1. Consume Shape ATC cookie from pool
//   2. POST /web_checkouts/v1/cart_items  →  cart created / item added
//   3. GET  /web_checkouts/v1/cart        →  verify item in cart
//   4. POST /web_checkouts/v1/checkout    →  init checkout, get checkoutId
//   5. PUT  /web_checkouts/v1/checkout/:id/address   →  set shipping
//   6. POST /web_checkouts/v1/checkout/:id/payment   →  set payment
//   7. POST /web_checkouts/v1/checkout/:id/place_order →  place order
//
// Notes on Shape:
//   - The ATC request (step 2) requires valid Shape cookies (_abck, bm_sz, etc.)
//   - These come from the cookie pool — generated by the Shape Harvester
//   - If the pool is empty the engine will wait up to `waitForCookieTimeoutMs`
//   - On a Shape block (409/429 with Shape error body): mark cookie consumed,
//     pull a new one from pool, retry up to `shapeRetryMax` times

import { SessionContext } from './session-manager'
import { consumeCookie, peekPool } from '../models/cookie-pool'
import { Profile, Account, Task, TaskSettings } from '../../shared/types'
import { getById } from '../storage/db'
import { adjustedNow } from '../utils/drop-timing'
import crypto from 'crypto'

// ─── Config ───────────────────────────────────────────────────────────────────

const TARGET_API = 'https://api.target.com'
const CHECKOUT_BASE = `${TARGET_API}/web_checkouts/v1`
const CARTS_BASE = `${TARGET_API}/web_checkouts/v1`   // same base, separate conceptually

// ─── Types ────────────────────────────────────────────────────────────────────

export interface CheckoutConfig {
  session: SessionContext
  profile: Profile
  tcin: string
  qty: number
  settings: TaskSettings
  taskId: number
  onStatus: (text: string) => void
  abortSignal: AbortSignal
}

export interface CheckoutResult {
  ok: boolean
  orderId?: string
  orderTotal?: number
  error?: string
  shapeBlocked?: boolean
  retryable?: boolean
  durationMs?: number
}

// ─── Address jig (match extension's jigAddressLine1 logic) ───────────────────

const JIG_CHARS = 'ABCDEFGHJKLMNPRSTUVWXYZ'

function jigAddress(address1: string, jigIndex: number): string {
  // Insert a letter suffix into the unit number to vary the shipping address
  // Same pattern as core/jigAddress.js in the extension
  const char = JIG_CHARS[Math.abs(jigIndex) % JIG_CHARS.length]
  // Try to insert after the street number
  const m = address1.match(/^(\d+)(.*)$/)
  if (m) return `${m[1]}${char}${m[2]}`
  return address1 + char
}

// ─── Main checkout engine ─────────────────────────────────────────────────────

export class CheckoutEngine {

  async run(cfg: CheckoutConfig): Promise<CheckoutResult> {
    const startMs = Date.now()

    try {
      return await this.runInternal(cfg)
    } catch (e: any) {
      return {
        ok: false,
        error: e.message,
        retryable: true,
        durationMs: Date.now() - startMs,
      }
    }
  }

  private async runInternal(cfg: CheckoutConfig): Promise<CheckoutResult> {
    const startMs = Date.now()
    const { session, profile, tcin, qty, settings, onStatus, abortSignal } = cfg

    // ── Step 0: Clear any open cart to avoid "cart in use" errors ─────────

    onStatus('Clearing cart...')
    await this.clearCart(session, abortSignal).catch(() => {
      // Non-fatal — if there's no cart or clearing fails, proceed anyway
    })

    // ── Step 1: Wait for / consume Shape cookie ────────────────────────────

    onStatus('Waiting for Shape cookie...')
    const COOKIE_WAIT_TIMEOUT_MS = 30_000
    const atcCookie = await this.waitForCookie(COOKIE_WAIT_TIMEOUT_MS, abortSignal)

    if (!atcCookie) {
      return { ok: false, error: 'No ATC cookie available in pool', retryable: false, durationMs: Date.now() - startMs }
    }

    // ── Step 2a: Add extra product (filler item, reduces cart-only block risk) ─

    if (settings.addExtraProduct && settings.extraProductTcin) {
      onStatus(`Adding filler item: ${settings.extraProductTcin}`)
      await this.addToCart(session, settings.extraProductTcin, 1, atcCookie.cookies, atcCookie.shapeHeaders, abortSignal)
        .catch(() => { /* filler failure is non-fatal */ })
    }

    // ── Step 2b: Add target item to Cart ──────────────────────────────────

    onStatus(`ATC: ${tcin}`)
    const atcResult = await this.addToCart(session, tcin, qty, atcCookie.cookies, atcCookie.shapeHeaders, abortSignal)

    if (!atcResult.ok) {
      if (atcResult.shapeBlocked) {
        return { ok: false, error: 'Shape block on ATC', shapeBlocked: true, retryable: true, durationMs: Date.now() - startMs }
      }
      if (atcResult.outOfStock) {
        return { ok: false, error: 'Out of stock at ATC', retryable: false, durationMs: Date.now() - startMs }
      }
      return { ok: false, error: atcResult.error, retryable: atcResult.retryable ?? true, durationMs: Date.now() - startMs }
    }

    const cartId = atcResult.cartId!
    onStatus('ATC success — initializing checkout...')

    // ── Step 3: Init checkout ──────────────────────────────────────────────

    const checkoutResult = await this.initCheckout(session, cartId, atcCookie.cookies, abortSignal)
    if (!checkoutResult.ok) {
      return { ok: false, error: `Checkout init failed: ${checkoutResult.error}`, retryable: true, durationMs: Date.now() - startMs }
    }

    const checkoutId = checkoutResult.checkoutId!
    onStatus('Setting shipping...')

    // ── Step 4: Set shipping address ───────────────────────────────────────

    const addressLine1 = profile.jigIndex >= 0
      ? jigAddress(profile.address1, profile.jigIndex)
      : profile.address1
    const shipResult = await this.setShipping(session, checkoutId, {
      ...profile,
      address1: addressLine1,
    }, atcCookie.cookies, abortSignal)

    if (!shipResult.ok) {
      return { ok: false, error: `Shipping step failed: ${shipResult.error}`, retryable: true, durationMs: Date.now() - startMs }
    }

    onStatus('Setting payment...')

    // ── Step 5: Set payment ────────────────────────────────────────────────

    const payResult = await this.setPayment(session, checkoutId, profile, atcCookie.cookies, abortSignal)
    if (!payResult.ok) {
      return { ok: false, error: `Payment step failed: ${payResult.error}`, retryable: true, durationMs: Date.now() - startMs }
    }

    // ── Step 6: Place order (if enabled) ──────────────────────────────────

    if (!settings.autoPlaceOrder) {
      onStatus('Stopped at review (auto place order is OFF)')
      return {
        ok: true,
        orderId: undefined,
        durationMs: Date.now() - startMs,
      }
    }

    onStatus('Placing order...')
    const orderResult = await this.placeOrder(session, checkoutId, atcCookie.cookies, abortSignal)
    if (!orderResult.ok) {
      return { ok: false, error: `Place order failed: ${orderResult.error}`, retryable: true, durationMs: Date.now() - startMs }
    }

    onStatus(`Order placed: ${orderResult.orderId}`)
    return {
      ok: true,
      orderId: orderResult.orderId,
      orderTotal: orderResult.orderTotal,
      durationMs: Date.now() - startMs,
    }
  }

  // ─── Clear Cart ───────────────────────────────────────────────────────────

  private async clearCart(session: SessionContext, signal: AbortSignal): Promise<void> {
    await this.fetch(`${CHECKOUT_BASE}/cart`, {
      method: 'DELETE',
      session,
      signal,
    })
  }

  // ─── ATC ──────────────────────────────────────────────────────────────────

  private async addToCart(
    session: SessionContext,
    tcin: string,
    qty: number,
    shapeCookies: Record<string, string>,
    shapeHeaders: Record<string, string>,
    signal: AbortSignal
  ): Promise<{ ok: boolean; cartId?: string; error?: string; shapeBlocked?: boolean; outOfStock?: boolean; retryable?: boolean }> {

    const body = {
      cart_type: 'REGULAR',
      cart_items: [{
        item_channels: { channel_id: 'WEB' },
        item_count: qty,
        tcin,
      }],
    }

    const resp = await this.fetch(`${CARTS_BASE}/cart_items`, {
      method: 'POST',
      session,
      shapeCookies,
      shapeHeaders,
      body,
      signal,
    })

    const data = await resp.json().catch(() => ({})) as any

    if (!resp.ok) {
      const status = resp.status
      // Shape block indicators
      if (status === 409 || status === 429) {
        const errCode = data?.error?.code || data?.code || ''
        if (String(errCode).includes('SHAPE') || String(errCode).includes('BLOCKED')) {
          return { ok: false, shapeBlocked: true, error: `Shape block: ${errCode}` }
        }
      }
      // Out of stock
      if (status === 422) {
        const errType = data?.error?.type || ''
        if (String(errType).includes('SELLABLE') || String(errType).includes('STOCK')) {
          return { ok: false, outOfStock: true, error: 'Item not sellable' }
        }
      }
      // Cart in use (another checkout is open)
      if (status === 409) {
        return { ok: false, error: 'Cart in use — clear cart and retry', retryable: true }
      }
      return { ok: false, error: `ATC HTTP ${status}`, retryable: status >= 500 }
    }

    const cartId = data?.cart?.cart_id || data?.cart_id || ''
    return { ok: true, cartId }
  }

  // ─── Init checkout ────────────────────────────────────────────────────────

  private async initCheckout(
    session: SessionContext,
    cartId: string,
    shapeCookies: Record<string, string>,
    signal: AbortSignal
  ): Promise<{ ok: boolean; checkoutId?: string; error?: string }> {

    const resp = await this.fetch(`${CHECKOUT_BASE}/checkout`, {
      method: 'POST',
      session,
      shapeCookies,
      body: { cart_id: cartId },
      signal,
    })

    const data = await resp.json().catch(() => ({})) as any

    if (!resp.ok) {
      return { ok: false, error: `Init checkout HTTP ${resp.status}` }
    }

    const checkoutId = data?.checkout?.checkout_id || data?.checkout_id || ''
    return { ok: true, checkoutId }
  }

  // ─── Set shipping ─────────────────────────────────────────────────────────

  private async setShipping(
    session: SessionContext,
    checkoutId: string,
    profile: Profile,
    shapeCookies: Record<string, string>,
    signal: AbortSignal
  ): Promise<{ ok: boolean; error?: string }> {

    const body = {
      address: {
        address_line1: profile.address1,
        address_line2: profile.address2 || undefined,
        city: profile.city,
        state: profile.state,
        zip_code: profile.zip,
        country: 'US',
        first_name: profile.firstName,
        last_name: profile.lastName,
        email: profile.email,
        phone_number: profile.phone.replace(/\D/g, ''),
        save_as_default: false,
      },
    }

    const resp = await this.fetch(`${CHECKOUT_BASE}/checkout/${checkoutId}/address`, {
      method: 'PUT',
      session,
      shapeCookies,
      body,
      signal,
    })

    if (!resp.ok) {
      const data = await resp.json().catch(() => ({})) as any
      return { ok: false, error: `Address HTTP ${resp.status}: ${JSON.stringify(data).slice(0, 200)}` }
    }

    return { ok: true }
  }

  // ─── Set payment ──────────────────────────────────────────────────────────

  private async setPayment(
    session: SessionContext,
    checkoutId: string,
    profile: Profile,
    shapeCookies: Record<string, string>,
    signal: AbortSignal
  ): Promise<{ ok: boolean; error?: string }> {

    const body = {
      payment_details: [{
        type: 'CREDIT_CARD',
        card_number: profile.cardNumber.replace(/\s/g, ''),
        expiration_month: profile.expMonth.padStart(2, '0'),
        expiration_year: profile.expYear.slice(-4),
        security_code: profile.cvv,
        billing_address: {
          zip_code: profile.billingZip || profile.zip,
          country: 'US',
        },
        is_default_payment: false,
      }],
    }

    const resp = await this.fetch(`${CHECKOUT_BASE}/checkout/${checkoutId}/payment`, {
      method: 'POST',
      session,
      shapeCookies,
      body,
      signal,
    })

    if (!resp.ok) {
      const data = await resp.json().catch(() => ({})) as any
      return { ok: false, error: `Payment HTTP ${resp.status}: ${JSON.stringify(data).slice(0, 200)}` }
    }

    return { ok: true }
  }

  // ─── Place order ──────────────────────────────────────────────────────────

  private async placeOrder(
    session: SessionContext,
    checkoutId: string,
    shapeCookies: Record<string, string>,
    signal: AbortSignal
  ): Promise<{ ok: boolean; orderId?: string; orderTotal?: number; error?: string }> {

    const resp = await this.fetch(`${CHECKOUT_BASE}/checkout/${checkoutId}/place_order`, {
      method: 'POST',
      session,
      shapeCookies,
      body: { checkout_id: checkoutId },
      signal,
    })

    const data = await resp.json().catch(() => ({})) as any

    if (!resp.ok) {
      const errMsg = data?.error?.message || data?.message || `HTTP ${resp.status}`
      return { ok: false, error: errMsg }
    }

    const orderId = data?.order?.id || data?.order_id || ''
    const orderTotal = data?.order?.total_amount || data?.total_amount || undefined

    return { ok: true, orderId, orderTotal }
  }

  // ─── Fetch wrapper ────────────────────────────────────────────────────────

  private async fetch(
    url: string,
    opts: {
      method: string
      session: SessionContext
      shapeCookies?: Record<string, string>
      shapeHeaders?: Record<string, string>
      body?: any
      signal: AbortSignal
    }
  ): Promise<Response> {
    const { method, session, shapeCookies, shapeHeaders, body, signal } = opts

    // Build cookie header: merge Shape cookies with session cookies
    const cookieMap: Record<string, string> = {
      visitorId: session.visitorId,
      ...shapeCookies,
    }
    const cookieHeader = Object.entries(cookieMap)
      .map(([k, v]) => `${k}=${v}`)
      .join('; ')

    const headers: Record<string, string> = {
      'accept': 'application/json',
      'accept-language': 'en-US,en;q=0.9',
      'content-type': 'application/json',
      'authorization': `Bearer ${session.accessToken}`,
      'x-api-key': session.apiKey,
      'x-application-name': 'web',
      'x-t-request-id': crypto.randomUUID(),
      'x-visitor-id': session.visitorId,
      'cookie': cookieHeader,
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
      'origin': 'https://www.target.com',
      'referer': 'https://www.target.com/checkout',
      // Pass through Shape-specific headers if available
      ...(shapeHeaders ?? {}),
    }

    return fetch(url, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
      signal,
    })
  }

  // ─── Wait for cookie ──────────────────────────────────────────────────────

  private async waitForCookie(
    timeoutMs: number,
    signal: AbortSignal
  ): Promise<ReturnType<typeof consumeCookie>> {
    const deadline = Date.now() + timeoutMs

    while (Date.now() < deadline) {
      if (signal.aborted) return null
      const cookie = consumeCookie('atc')
      if (cookie) return cookie
      await sleep(500)
    }

    // Timeout — try login cookie as fallback
    return consumeCookie('login')
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise(r => setTimeout(r, ms))
}

export const checkoutEngine = new CheckoutEngine()
