/**
 * Local HTTP server for FIX-2 fixture e2e — serves MOCK_URLS HTML on retailer hostnames
 * via Chrome --host-resolver-rules (127.0.0.1) + explicit port in test URLs.
 */
import { createServer } from 'node:http';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MOCK_URLS } from './test-scope.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Retailer hostname + path → fixture file (paths from fixtures' data-tch-path).
 * @type {Array<{ host: string, path: string, file: string, initLog: string, journey: string }>}
 */
export const FIXTURE_E2E_ROUTES = [
  {
    host: 'www.target.com',
    path: '/p/mock-product',
    file: MOCK_URLS.targetProduct,
    initLog: '[TCH] init',
    journey: 'TGT-1',
    invariants: ['tgt-live-poll-cycle', 'mon2-live-poll-cycle', 'mon2-samsclub-live-poll-cycle'],
    monitorProductPath: '/p/mock-product',
  },
  {
    host: 'www.target.com',
    path: '/checkout',
    file: MOCK_URLS.targetCheckoutReview,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [
      'no-sacred-lock',
      'tgt4-manual-review',
      'tgt4-live-poll-cycle',
      'tgt-poll-recovery-rearm',
      'mon2-live-poll-cycle',
      'mon2-samsclub-live-poll-cycle',
    ],
    monitorProductPath: '/p/mock-product',
    pollRecoveryProductPath: '/p/mock-review-recovery/A-880100',
  },
  {
    host: 'www.target.com',
    path: '/p/mock-review-recovery/A-880100',
    file: MOCK_URLS.targetProductReviewRecovery,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/checkout/review-cross',
    file: MOCK_URLS.targetCheckoutReviewCross,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [
      'no-sacred-lock',
      'tgt4-manual-review',
      'tgt4-live-poll-cycle',
      'tgt-poll-recovery-rearm',
    ],
    monitorProductPath: '/p/mock-review-cross-monitor/A-880101',
    pollRecoveryProductPath: '/p/mock-review-cross-recovery/A-880102',
  },
  {
    host: 'www.target.com',
    path: '/p/mock-review-cross-monitor/A-880101',
    file: MOCK_URLS.targetProductReviewCrossMonitor,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/p/mock-review-cross-recovery/A-880102',
    file: MOCK_URLS.targetProductReviewCrossRecovery,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/checkout/signin-gate',
    file: MOCK_URLS.targetCheckoutSignin,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [
      'no-sacred-lock',
      'tgt-checkout-signin',
      'tgt-signin-live-poll-cycle',
      'tgt-poll-recovery-rearm',
      'mon2-live-poll-cycle',
    ],
    monitorProductPath: '/p/mock-product',
    pollRecoveryProductPath: '/p/mock-signin-recovery/A-880099',
  },
  {
    host: 'www.target.com',
    path: '/p/mock-signin-recovery/A-880099',
    file: MOCK_URLS.targetProductSigninRecovery,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/checkout/signin-gate-cross',
    file: MOCK_URLS.targetCheckoutSigninCross,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [
      'no-sacred-lock',
      'tgt-checkout-signin',
      'tgt-signin-live-poll-cycle',
      'tgt-poll-recovery-rearm',
    ],
    monitorProductPath: '/p/mock-signin-cross-monitor/A-880097',
    pollRecoveryProductPath: '/p/mock-signin-cross-recovery/A-880098',
  },
  {
    host: 'www.target.com',
    path: '/p/mock-signin-cross-monitor/A-880097',
    file: MOCK_URLS.targetProductSigninCrossMonitor,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/p/mock-signin-cross-recovery/A-880098',
    file: MOCK_URLS.targetProductSigninCrossRecovery,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/checkout/spa-stall',
    file: MOCK_URLS.targetCheckoutSpaTimeout,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [
      'no-sacred-lock',
      'nav-failed-releases-lock',
      'tgt4-checkout-spa-timeout',
      'tgt4-checkout-spa-live-poll-cycle',
      'tgt-poll-recovery-rearm',
      'tgt-repeated-nav-failed',
    ],
    monitorProductPath: '/p/mock-checkout-spa-stall/794',
    pollRecoveryProductPath: '/p/-/A-77777777',
    checkoutTimeoutMs: 750,
  },
  {
    host: 'www.target.com',
    path: '/p/mock-checkout-spa-stall/794',
    file: MOCK_URLS.targetProduct,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/checkout/spa-stall-cross',
    file: MOCK_URLS.targetCheckoutSpaCross,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [
      'no-sacred-lock',
      'nav-failed-releases-lock',
      'tgt4-checkout-spa-timeout',
      'tgt4-checkout-spa-live-poll-cycle',
      'tgt-poll-recovery-rearm',
      'tgt-repeated-nav-failed',
    ],
    monitorProductPath: '/p/mock-checkout-spa-cross-monitor/A-880092',
    pollRecoveryProductPath: '/p/mock-checkout-spa-cross-recovery/A-880093',
    checkoutTimeoutMs: 750,
  },
  {
    host: 'www.target.com',
    path: '/p/mock-checkout-spa-cross-monitor/A-880092',
    file: MOCK_URLS.targetProductCheckoutSpaCrossMonitor,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/p/mock-checkout-spa-cross-recovery/A-880093',
    file: MOCK_URLS.targetProductCheckoutSpaCrossRecovery,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/cart/no-checkout',
    file: MOCK_URLS.targetCartNoCheckout,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [
      'no-sacred-lock',
      'tgt-cart-checkout-missing',
      'tgt-cart-live-poll-cycle',
      'tgt-poll-recovery-rearm',
      'nav-failed-releases-lock',
    ],
    monitorProductPath: '/p/-/A-88888888',
    pollRecoveryProductPath: '/p/-/A-77777777',
    cartCheckoutWaitMs: 750,
  },
  {
    host: 'www.target.com',
    path: '/cart/no-checkout-cross',
    file: MOCK_URLS.targetCartNoCheckoutCross,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [
      'no-sacred-lock',
      'tgt-cart-checkout-missing',
      'tgt-cart-live-poll-cycle',
      'tgt-poll-recovery-rearm',
      'nav-failed-releases-lock',
    ],
    monitorProductPath: '/p/mock-cart-cross-monitor/A-880088',
    pollRecoveryProductPath: '/p/mock-cart-cross-recovery/A-880089',
    cartCheckoutWaitMs: 750,
  },
  {
    host: 'www.target.com',
    path: '/p/mock-cart-cross-monitor/A-880088',
    file: MOCK_URLS.targetProductCartCrossMonitor,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/p/mock-cart-cross-recovery/A-880089',
    file: MOCK_URLS.targetProductCartCrossRecovery,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/p/-/A-88888888',
    file: MOCK_URLS.targetProduct,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/p/-/A-77777777',
    file: MOCK_URLS.targetProduct,
    initLog: '[TCH] init',
    journey: 'TGT-4',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/p/-/A-66666666',
    file: MOCK_URLS.targetProductNoAtc,
    initLog: '[TCH] init',
    journey: 'TGT-1',
    invariants: [
      'no-sacred-lock',
      'nav-failed-releases-lock',
      'tgt-missing-atc-element',
      'tgt-repeated-nav-failed',
      'tgt-live-poll-cycle',
      'tgt-poll-recovery-rearm',
    ],
    monitorProductPath: '/p/-/A-66666666',
    pollRecoveryProductPath: '/p/-/A-66666666',
    atcWaitMs: 750,
  },
  {
    host: 'www.target.com',
    path: '/p/mock-missing-atc-cross/A-880095',
    file: MOCK_URLS.targetProductMissingAtcCross,
    initLog: '[TCH] init',
    journey: 'TGT-1',
    invariants: [
      'no-sacred-lock',
      'nav-failed-releases-lock',
      'tgt-missing-atc-element',
      'tgt-repeated-nav-failed',
      'tgt-live-poll-cycle',
      'tgt-poll-recovery-rearm',
    ],
    monitorProductPath: '/p/mock-missing-atc-cross-monitor/A-880094',
    pollRecoveryProductPath: '/p/mock-missing-atc-cross-recovery/A-880096',
    atcWaitMs: 750,
  },
  {
    host: 'www.target.com',
    path: '/p/mock-missing-atc-cross-monitor/A-880094',
    file: MOCK_URLS.targetProductMissingAtcCrossMonitor,
    initLog: '[TCH] init',
    journey: 'TGT-1',
    invariants: [],
  },
  {
    host: 'www.target.com',
    path: '/p/mock-missing-atc-cross-recovery/A-880096',
    file: MOCK_URLS.targetProductMissingAtcCrossRecovery,
    initLog: '[TCH] init',
    journey: 'TGT-1',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-predrop/123',
    file: MOCK_URLS.walmartProductPreDrop,
    initLog: '[WMT] init',
    journey: 'WM-2',
    invariants: [
      'no-sacred-lock',
      'nav-failed-releases-lock',
      'wm2-repeated-nav-failed',
      'wm2-live-poll-cycle',
      'mon2-samsclub-live-poll-cycle',
    ],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-queue/456',
    file: MOCK_URLS.walmartProductQueue,
    initLog: '[WMT] init',
    journey: 'WM-4',
    invariants: [
      'sacred-lock',
      'wm5-sacred-survives-nav-failed',
      'wm5-pre-timeout-live-poll-cycle',
      'wm5-live-poll-cycle',
    ],
    monitorProductPath: '/ip/mock-queue/456',
  },
  {
    host: 'www.walmart.com',
    path: '/qp/waiting-room',
    file: MOCK_URLS.walmartQpRoom,
    initLog: '[WMT] init',
    journey: 'WM-4',
    invariants: ['no-sacred-lock', 'wm4-qp-no-producturl', 'wm4-live-poll-cycle'],
  },
  {
    host: 'www.walmart.com',
    path: '/qp/waiting-room-monitored',
    file: MOCK_URLS.walmartQpRoom,
    initLog: '[WMT] init',
    journey: 'WM-4',
    invariants: [
      'sacred-lock-qp',
      'wm5-sacred-survives-nav-failed',
      'wm5-pre-timeout-live-poll-cycle',
      'wm5-live-poll-cycle',
    ],
    sacredLockProductPath: '/ip/mock-qp-product/999',
  },
  {
    host: 'www.walmart.com',
    path: '/checkout',
    file: MOCK_URLS.walmartCheckoutQueue,
    initLog: '[WMT] init',
    journey: 'WM-6',
    invariants: [
      'sacred-lock-checkout',
      'wm5-sacred-survives-nav-failed',
      'wm5-pre-timeout-live-poll-cycle',
      'wm5-live-poll-cycle',
    ],
    sacredLockProductPath: '/ip/mock-wm6-checkout/789',
  },
  {
    host: 'www.walmart.com',
    path: '/checkout/unmonitored',
    file: MOCK_URLS.walmartCheckoutQueue,
    initLog: '[WMT] init',
    journey: 'WM-4',
    invariants: [
      'no-sacred-lock',
      'wm4-checkout-no-producturl',
      'wm4-live-poll-cycle',
      'mon2-samsclub-live-poll-cycle',
    ],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-queue-poll/457',
    file: MOCK_URLS.walmartProductQueuePollCross,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [
      'wm5-pre-timeout-live-poll-cycle',
      'wm5-product-queue-timeout',
      'wm5-queue-timeout-clears-sacred-lock',
      'wm5-poll-recovery-rearm',
    ],
    monitorProductPath: '/ip/mock-queue/456',
    sacredLockProductPath: '/ip/mock-queue/456',
    pollRecoveryProductPath: '/ip/mock-queue-poll-recovery/461',
    queueTimeoutMs: 5000,
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-queue-poll-recovery/461',
    file: MOCK_URLS.walmartProductQueuePollCrossRecovery,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-px/555',
    file: MOCK_URLS.walmartProductPx,
    initLog: '[WMT] PX/loading page detected',
    journey: 'WM-6',
    invariants: [
      'no-sacred-lock',
      'px-timeout-nav-failed',
      'wm6-live-poll-cycle',
      'wm6-poll-recovery-rearm',
    ],
    sacredLockProductPath: '/ip/mock-px/555',
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-px-captcha/556',
    file: MOCK_URLS.walmartProductPxCaptcha,
    initLog: '[WMT] PX/loading page detected',
    journey: 'WM-6',
    invariants: [
      'no-sacred-lock',
      'px-timeout-nav-failed',
      'wm6-live-poll-cycle',
      'wm6-poll-recovery-rearm',
    ],
    sacredLockProductPath: '/ip/mock-px-captcha/556',
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-px-block/557',
    file: MOCK_URLS.walmartProductPxBlock,
    initLog: '[WMT] PX/loading page detected',
    journey: 'WM-6',
    invariants: [
      'no-sacred-lock',
      'px-timeout-nav-failed',
      'wm6-live-poll-cycle',
      'wm6-poll-recovery-rearm',
    ],
    sacredLockProductPath: '/ip/mock-px-block/557',
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-no-atc/559',
    file: MOCK_URLS.walmartProductNoAtc,
    initLog: '[WMT] init',
    journey: 'WM-6',
    invariants: [
      'no-sacred-lock',
      'nav-failed-releases-lock',
      'wm6-missing-atc-element',
      'wm6-repeated-nav-failed',
      'wm6-live-poll-cycle',
      'wm6-poll-recovery-rearm',
    ],
    monitorProductPath: '/ip/mock-no-atc/559',
    atcWaitMs: 750,
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-px-override/558',
    file: MOCK_URLS.walmartProductPxOverride,
    initLog: '[WMT] PX/loading page detected',
    journey: 'WM-6',
    invariants: [
      'no-sacred-lock',
      'px-timeout-nav-failed',
      'px-timeout-ms-override',
      'wm6-live-poll-cycle',
      'wm6-poll-recovery-rearm',
    ],
    sacredLockProductPath: '/ip/mock-px-override/558',
    pxTimeoutMs: 750,
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-mon2-target-live/333',
    file: MOCK_URLS.walmartProductNoAtc,
    initLog: '[WMT] init',
    journey: 'MON-2',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-oid/777',
    file: MOCK_URLS.walmartProductOid,
    initLog: '[WMT] init',
    journey: 'WM-7',
    invariants: ['wm7-offer-id-ready'],
    monitorProductPath: '/ip/mock-oid/777',
    expectedOfferId: 'FIXTURE-OID-WM7-777',
  },
  {
    host: 'www.walmart.com',
    path: '/cart/no-checkout',
    file: MOCK_URLS.walmartCartNoCheckout,
    initLog: '[WMT] init',
    journey: 'WM-6',
    invariants: ['no-sacred-lock', 'wm6-cart-checkout-missing', 'wm6-cart-live-poll-cycle', 'wm6-poll-recovery-rearm'],
    monitorProductPath: '/ip/mock-cart-missing/888',
    pollRecoveryProductPath: '/ip/mock-no-atc/559',
  },
  {
    host: 'www.walmart.com',
    path: '/cart/no-checkout-cross',
    file: MOCK_URLS.walmartCartNoCheckoutCross,
    initLog: '[WMT] init',
    journey: 'WM-6',
    invariants: [
      'no-sacred-lock',
      'wm6-cart-checkout-missing',
      'wm6-cart-live-poll-cycle',
      'wm6-poll-recovery-rearm',
      'wm6-repeated-nav-failed',
      'nav-failed-releases-lock',
    ],
    monitorProductPath: '/ip/mock-cart-cross-monitor/890',
    pollRecoveryProductPath: '/ip/mock-cart-cross-recovery/891',
    cartCheckoutWaitMs: 750,
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-cart-cross-monitor/890',
    file: MOCK_URLS.walmartProductCartCrossMonitor,
    initLog: '[WMT] init',
    journey: 'WM-6',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-cart-cross-recovery/891',
    file: MOCK_URLS.walmartProductCartCrossRecovery,
    initLog: '[WMT] init',
    journey: 'WM-6',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-cart-missing/888',
    file: MOCK_URLS.walmartProductCartMissing,
    initLog: '[WMT] init',
    journey: 'WM-6',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/qp/waiting-room-timeout',
    file: MOCK_URLS.walmartQpRoomTimeout,
    initLog: '[WMT] init',
    journey: 'WM-6',
    invariants: [
      'no-sacred-lock',
      'wm4-qp-timeout-no-producturl',
      'wm4-live-poll-cycle',
      'wm4-poll-recovery-rearm',
    ],
    pollRecoveryProductPath: '/ip/mock-qp-unmonitored-recovery/996',
    queueTimeoutMs: 750,
  },
  {
    host: 'www.walmart.com',
    path: '/qp/waiting-room-monitored-timeout',
    file: MOCK_URLS.walmartQpRoomMonitoredPretimeout,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [
      'wm5-pre-timeout-live-poll-cycle',
      'wm4-qp-timeout-with-producturl',
      'wm5-queue-timeout-clears-sacred-lock',
      'wm5-poll-recovery-rearm',
      'wm4-live-poll-cycle',
    ],
    sacredLockProductPath: '/ip/mock-qp-timeout-monitored/994',
    pollRecoveryProductPath: '/ip/mock-qp-timeout-monitored-recovery/998',
    queueTimeoutMs: 5000,
  },
  {
    host: 'www.walmart.com',
    path: '/checkout/unmonitored-timeout',
    file: MOCK_URLS.walmartCheckoutQueueTimeout,
    initLog: '[WMT] init',
    journey: 'WM-6',
    invariants: [
      'no-sacred-lock',
      'wm4-checkout-timeout-no-producturl',
      'wm4-live-poll-cycle',
      'wm4-poll-recovery-rearm',
    ],
    pollRecoveryProductPath: '/ip/mock-checkout-unmonitored-recovery/997',
    queueTimeoutMs: 750,
  },
  {
    host: 'www.walmart.com',
    path: '/checkout/monitored-timeout',
    file: MOCK_URLS.walmartCheckoutMonitoredPretimeout,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [
      'wm5-pre-timeout-live-poll-cycle',
      'wm4-checkout-timeout-with-producturl',
      'wm5-queue-timeout-clears-sacred-lock',
      'wm5-poll-recovery-rearm',
      'wm4-live-poll-cycle',
    ],
    sacredLockProductPath: '/ip/mock-checkout-timeout-monitored/995',
    pollRecoveryProductPath: '/ip/mock-checkout-timeout-monitored-recovery/999',
    queueTimeoutMs: 5000,
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-product-queue-pretimeout/460',
    file: MOCK_URLS.walmartProductQueuePretimeout,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [
      'wm5-pre-timeout-live-poll-cycle',
      'wm5-product-queue-timeout',
      'wm5-queue-timeout-clears-sacred-lock',
      'wm5-poll-recovery-rearm',
    ],
    monitorProductPath: '/ip/mock-product-queue-pretimeout/460',
    pollRecoveryProductPath: '/ip/mock-product-queue-timeout-recovery/459',
    queueTimeoutMs: 5000,
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-product-queue-timeout/458',
    file: MOCK_URLS.walmartProductQueueTimeout,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [
      'wm5-product-queue-timeout',
      'wm5-queue-timeout-clears-sacred-lock',
      'wm5-poll-recovery-rearm',
    ],
    monitorProductPath: '/ip/mock-product-queue-timeout/458',
    pollRecoveryProductPath: '/ip/mock-product-queue-timeout-recovery/459',
    queueTimeoutMs: 750,
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-price-guard-timeout/991',
    file: MOCK_URLS.walmartProductPriceGuardTimeout,
    initLog: '[WMT] init',
    journey: 'WM-6',
    invariants: [
      'no-sacred-lock',
      'wm6-price-guard-timeout',
      'wm6-live-poll-cycle',
      'wm6-poll-recovery-rearm',
    ],
    monitorProductPath: '/ip/mock-price-guard-timeout/991',
    walmartMaxPrice: 50,
    priceGuardTimeoutMs: 750,
  },
  {
    host: 'www.walmart.com',
    path: '/checkout/spa-stall',
    file: MOCK_URLS.walmartCheckoutSpaTimeout,
    initLog: '[WMT] init',
    journey: 'WM-6',
    invariants: [
      'no-sacred-lock',
      'wm6-checkout-spa-timeout',
      'wm6-live-poll-cycle',
      'wm6-poll-recovery-rearm',
    ],
    monitorProductPath: '/ip/mock-checkout-spa/992',
    checkoutTimeoutMs: 750,
  },
  {
    host: 'www.walmart.com',
    path: '/checkout/spa-stall-sacred',
    file: MOCK_URLS.walmartCheckoutSpaSacred,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [
      'wm5-checkout-spa-timeout-clears-sacred-lock',
      'wm5-checkout-spa-live-poll-cycle',
      'wm5-poll-recovery-rearm',
    ],
    monitorProductPath: '/ip/mock-checkout-spa-sacred/996',
    pollRecoveryProductPath: '/ip/mock-checkout-spa-sacred-recovery/997',
    checkoutTimeoutMs: 5000,
  },
  {
    host: 'www.walmart.com',
    path: '/checkout/spa-stall-sacred-cross',
    file: MOCK_URLS.walmartCheckoutSpaSacredCross,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [
      'wm5-checkout-spa-timeout-clears-sacred-lock',
      'wm5-checkout-spa-live-poll-cycle',
      'wm5-poll-recovery-rearm',
    ],
    monitorProductPath: '/ip/mock-checkout-spa-cross-monitor/1002',
    pollRecoveryProductPath: '/ip/mock-checkout-spa-cross-recovery/1004',
    checkoutTimeoutMs: 5000,
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-checkout-spa/992',
    file: MOCK_URLS.walmartProductNoAtc,
    initLog: '[WMT] init',
    journey: 'WM-6',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-checkout-spa-sacred/996',
    file: MOCK_URLS.walmartProductNoAtc,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-checkout-spa-sacred-recovery/997',
    file: MOCK_URLS.walmartProductNoAtc,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-checkout-spa-cross-monitor/1002',
    file: MOCK_URLS.walmartProductNoAtc,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-checkout-spa-cross-recovery/1004',
    file: MOCK_URLS.walmartProductNoAtc,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-qp-timeout-monitored/994',
    file: MOCK_URLS.walmartProductPollRecovery,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-product-queue-timeout-recovery/459',
    file: MOCK_URLS.walmartProductQueuePollRecovery,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-checkout-timeout-monitored/995',
    file: MOCK_URLS.walmartCheckoutPollRecovery,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-qp-unmonitored-recovery/996',
    file: MOCK_URLS.walmartProductNoAtc,
    initLog: '[WMT] init',
    journey: 'WM-4',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-checkout-unmonitored-recovery/997',
    file: MOCK_URLS.walmartProductNoAtc,
    initLog: '[WMT] init',
    journey: 'WM-4',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-qp-timeout-monitored-recovery/998',
    file: MOCK_URLS.walmartProductNoAtc,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [],
  },
  {
    host: 'www.walmart.com',
    path: '/ip/mock-checkout-timeout-monitored-recovery/999',
    file: MOCK_URLS.walmartProductNoAtc,
    initLog: '[WMT] init',
    journey: 'WM-5',
    invariants: [],
  },
  {
    host: 'www.samsclub.com',
    path: '/cart',
    file: MOCK_URLS.samsclubCart,
    initLog: '[TCH] init',
    journey: 'SC-2',
    invariants: ['no-sacred-lock', 'sc2-cart-checkout', 'sc5-sc6-live-poll-cycle'],
    monitorProductPath: '/p/mock-fcfs/789',
  },
  {
    host: 'www.samsclub.com',
    path: '/cart/no-checkout',
    file: MOCK_URLS.samsclubCartNoCheckout,
    initLog: '[TCH] init',
    journey: 'SC-6',
    invariants: [
      'no-sacred-lock',
      'sc2-cart-checkout-missing',
      'sc6-cart-live-poll-cycle',
      'sc6-poll-recovery-rearm',
      'nav-failed-releases-lock',
    ],
    monitorProductPath: '/p/mock-fcfs-cart-missing/792',
    pollRecoveryProductPath: '/p/mock-fcfs-invisible-atc/791',
    cartCheckoutWaitMs: 750,
  },
  {
    host: 'www.samsclub.com',
    path: '/cart/no-checkout-cross',
    file: MOCK_URLS.samsclubCartNoCheckoutCross,
    initLog: '[TCH] init',
    journey: 'SC-6',
    invariants: [
      'no-sacred-lock',
      'sc2-cart-checkout-missing',
      'sc6-cart-live-poll-cycle',
      'sc6-poll-recovery-rearm',
      'sc6-repeated-nav-failed',
      'nav-failed-releases-lock',
    ],
    monitorProductPath: '/p/mock-fcfs-cart-cross-monitor/794',
    pollRecoveryProductPath: '/p/mock-fcfs-cart-cross-recovery/795',
    cartCheckoutWaitMs: 750,
  },
  {
    host: 'www.samsclub.com',
    path: '/p/mock-fcfs-cart-cross-monitor/794',
    file: MOCK_URLS.samsclubProductCartCrossMonitor,
    initLog: '[TCH] init',
    journey: 'SC-6',
    invariants: [],
  },
  {
    host: 'www.samsclub.com',
    path: '/p/mock-fcfs-cart-cross-recovery/795',
    file: MOCK_URLS.samsclubProductCartCrossRecovery,
    initLog: '[TCH] init',
    journey: 'SC-6',
    invariants: [],
  },
  {
    host: 'www.samsclub.com',
    path: '/p/mock-fcfs-cart-missing/792',
    file: MOCK_URLS.samsclubProductCartMissing,
    initLog: '[TCH] init',
    journey: 'SC-6',
    invariants: [],
  },
  {
    host: 'www.samsclub.com',
    path: '/checkout',
    file: MOCK_URLS.samsclubCheckoutReview,
    initLog: '[TCH] init',
    journey: 'SC-4',
    invariants: [
      'sc4-manual-review',
      'sc4-live-poll-cycle',
      'sc5-sc6-live-poll-cycle',
    ],
    monitorProductPath: '/p/mock-fcfs/789',
  },
  {
    host: 'www.samsclub.com',
    path: '/checkout/spa',
    file: MOCK_URLS.samsclubCheckoutSpa,
    initLog: '[TCH] init',
    journey: 'SC-4',
    invariants: [
      'no-sacred-lock',
      'sc4-shipping-payment-review',
      'sc4-manual-review',
      'sc5-sc6-live-poll-cycle',
    ],
    monitorProductPath: '/p/mock-fcfs/789',
  },
  {
    host: 'www.samsclub.com',
    path: '/checkout/spa-stall',
    file: MOCK_URLS.samsclubCheckoutSpaTimeout,
    initLog: '[TCH] init',
    journey: 'SC-4',
    invariants: [
      'no-sacred-lock',
      'nav-failed-releases-lock',
      'sc4-checkout-spa-timeout',
      'sc4-repeated-nav-failed',
      'sc6-checkout-spa-live-poll-cycle',
      'sc4-poll-recovery-rearm',
    ],
    monitorProductPath: '/p/mock-checkout-spa-stall/793',
    pollRecoveryProductPath: '/p/mock-fcfs-invisible-atc/791',
    checkoutTimeoutMs: 750,
  },
  {
    host: 'www.samsclub.com',
    path: '/p/mock-checkout-spa-stall/793',
    file: MOCK_URLS.samsclubProductFcfsRestock,
    initLog: '[TCH] init',
    journey: 'SC-4',
    invariants: [],
  },
  {
    host: 'www.samsclub.com',
    path: '/checkout/spa-stall-cross',
    file: MOCK_URLS.samsclubCheckoutSpaCross,
    initLog: '[TCH] init',
    journey: 'SC-6',
    invariants: [
      'no-sacred-lock',
      'nav-failed-releases-lock',
      'sc4-checkout-spa-timeout',
      'sc4-repeated-nav-failed',
      'sc6-checkout-spa-live-poll-cycle',
      'sc4-poll-recovery-rearm',
    ],
    monitorProductPath: '/p/mock-checkout-spa-cross-monitor/796',
    pollRecoveryProductPath: '/p/mock-checkout-spa-cross-recovery/797',
    checkoutTimeoutMs: 750,
  },
  {
    host: 'www.samsclub.com',
    path: '/p/mock-checkout-spa-cross-monitor/796',
    file: MOCK_URLS.samsclubProductCheckoutSpaCrossMonitor,
    initLog: '[TCH] init',
    journey: 'SC-6',
    invariants: [],
  },
  {
    host: 'www.samsclub.com',
    path: '/p/mock-checkout-spa-cross-recovery/797',
    file: MOCK_URLS.samsclubProductCheckoutSpaCrossRecovery,
    initLog: '[TCH] init',
    journey: 'SC-6',
    invariants: [],
  },
  {
    host: 'www.samsclub.com',
    path: '/p/mock-fcfs-disabled/792',
    file: MOCK_URLS.samsclubProductFcfsDisabled,
    initLog: '[TCH] init',
    journey: 'SC-3',
    invariants: [
      'no-sacred-lock',
      'nav-failed-releases-lock',
      'sc3-disabled-atc',
      'sc3-poll-recovery-rearm',
      'sc5-sc6-live-poll-cycle',
    ],
    monitorProductPath: '/p/mock-fcfs-disabled/792',
    monitorQty: 5,
    atcWaitMs: 750,
  },
  {
    host: 'www.samsclub.com',
    path: '/p/mock-fcfs/789',
    file: MOCK_URLS.samsclubProductFcfs,
    initLog: '[TCH] init',
    journey: 'SC-3',
    invariants: ['no-sacred-lock', 'sc5-repeated-atc-success', 'sc5-sc6-live-poll-cycle'],
    monitorProductPath: '/p/mock-fcfs/789',
    monitorQty: 5,
  },
  {
    host: 'www.samsclub.com',
    path: '/p/mock-fcfs-restock/790',
    file: MOCK_URLS.samsclubProductFcfsRestock,
    initLog: '[TCH] init',
    journey: 'SC-6',
    invariants: [
      'no-sacred-lock',
      'nav-failed-releases-lock',
      'sc6-repeated-nav-failed',
      'sc5-repeated-atc-success',
      'sc6-poll-recovery-rearm',
      'sc5-sc6-live-poll-cycle',
    ],
    monitorProductPath: '/p/mock-fcfs-restock/790',
    monitorQty: 5,
    atcWaitMs: 750,
  },
  {
    host: 'www.samsclub.com',
    path: '/p/mock-fcfs-invisible-atc/791',
    file: MOCK_URLS.samsclubProductFcfsInvisibleAtc,
    initLog: '[TCH] init',
    journey: 'SC-6',
    invariants: [
      'no-sacred-lock',
      'nav-failed-releases-lock',
      'sc6-repeated-nav-failed',
      'sc6-invisible-atc',
      'sc6-poll-recovery-rearm',
      'sc5-sc6-live-poll-cycle',
    ],
    monitorProductPath: '/p/mock-fcfs-invisible-atc/791',
    monitorQty: 5,
    atcWaitMs: 750,
  },
  {
    host: 'www.samsclub.com',
    path: '/p/mock-mon2-walmart-live/444',
    file: MOCK_URLS.samsclubProductFcfs,
    initLog: '[TCH] init',
    journey: 'MON-2',
    invariants: [],
  },
];

/** Hostnames mapped to 127.0.0.1 for Chrome host-resolver-rules. */
export const FIXTURE_HOSTS = [...new Set(FIXTURE_E2E_ROUTES.map((r) => r.host))];

/**
 * @param {{ routes?: typeof FIXTURE_E2E_ROUTES }} [options]
 * @returns {Promise<{ server: import('node:http').Server, port: number, close: () => Promise<void> }>}
 */
export function startFixtureServer(options = {}) {
  const routes = options.routes || FIXTURE_E2E_ROUTES;
  const routeKey = (host, pathname) => `${host.toLowerCase()}|${pathname}`;

  const lookup = new Map();
  for (const route of routes) {
    lookup.set(routeKey(route.host, route.path), route);
  }

  const server = createServer((req, res) => {
    const host = (req.headers.host || '').split(':')[0].toLowerCase();
    const pathname = (req.url || '/').split('?')[0];
    const route = lookup.get(routeKey(host, pathname));
    if (!route) {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      res.end(`fixture not found: ${host}${pathname}`);
      return;
    }
    const abs = join(__dirname, route.file);
    try {
      const body = readFileSync(abs, 'utf8');
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      res.end(body);
    } catch (err) {
      res.writeHead(500, { 'Content-Type': 'text/plain' });
      res.end(String(err));
    }
  });

  return new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const addr = server.address();
      const port = typeof addr === 'object' && addr ? addr.port : 0;
      resolve({
        server,
        port,
        close: () =>
          new Promise((res, rej) => {
            server.close((err) => (err ? rej(err) : res()));
          }),
      });
    });
  });
}

/** Chrome --host-resolver-rules value for FIXTURE_HOSTS → 127.0.0.1 */
export function hostResolverRules() {
  return FIXTURE_HOSTS.map((h) => `MAP ${h} 127.0.0.1`).join(', ');
}
